name: Identity Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
    paths:
      # Rutas actualizadas
      - 'TiendaInspireIdentity/**'
      - 'TiendaInspire.ServiceDefaults/**'
      - 'TiendaInspire.Shared/**'
      - 'test' 
      - '.github/workflows/identity-docker.yml' 
  pull_request:
    branches: [ "main", "master" ]
    paths:
      # Rutas actualizadas
      - 'TiendaInspireIdentity/**'
      - 'TiendaInspire.ServiceDefaults/**'
      - 'TiendaInspire.Shared/**'
      - '.github/workflows/identity-docker.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/identity-api-image

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Crucial permission for pushing to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # --- ADD THIS STEP ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ---------------------

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./TiendaInspireIdentity/Dockerfile
          push: true
          # Remove `load: true` as it is not needed when `push: true`
          # load: true # <--- REMOVE THIS LINE
          
          # --- UPDATE THIS TAG TO USE THE ENV VARIABLES ---
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          # ------------------------------------------------
          
          cache-from: type=gha
          cache-to: type=gha,mode=max


