name: Build Docker Image
uses: write
with:
  context:
  file: ./TiendaInspireIdentity/Dockerfile
  push: false
  load: true
  tags: identity-api:test
  cache-from : type=gah
  cache-to: type=gha,mode=max
 


      